name: Build and Push to GHCR.IO

on:
  push:
    branches:
    - develop

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Build:checkout
        uses: actions/checkout@v2
      - name: Build:dockerimage
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "sophanith2020"
          password: ${{ secrets.GHCIO }}
          repository: mbanq/watchman
          tags: dev-latest
